Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(test.py:48909): Gdk-CRITICAL **: 13:20:33.422: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
